apiVersion: v2
name: bascinet
description: A general-purpose Interledger shaped chart for easy generic deployments.
home: https://github.com/interledger/charts
icon: https://interledger.github.io/charts/icons/bascinet.png

type: application
version: 0.2.0
appVersion: "v0.0.0"

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
