{{- define "rafiki.pos.SecretsMap" -}}
{{- end }}
{{- if and .Values.config.pos.enabled .Values.config.pos.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.pos "rafiki.pos.SecretsMap") }}
{{- end }}
