{{- define "rafiki.cards.SecretsMap" -}}
{{- end }}
{{- if and .Values.config.cards.enabled .Values.config.cards.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.cards "rafiki.cards.SecretsMap") }}
{{- end }}
