{{- define "backend.deployment" -}}
{{- $top := first . }}
{{- if $top.Values.backend.enabled }}
{{- $dataHash := ($top.Values.backend.config | default dict) | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        bascinet-backend-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- include "common.deployment" (list . .Values.backend .Values.backend.autoscaling .Values.backend.serviceAccount "backend.deployment") }}
