{{- define "api.deployment" -}}
{{- $top := first . }}
{{- if $top.Values.api.enabled }}
{{- $dataHash := ($top.Values.api.config | default dict) | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        bascinet-api-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- include "common.deployment" (list . .Values.api .Values.api.autoscaling .Values.api.serviceAccount "api.deployment") }}
